name: Halium Generic Adaptation Build

on:
  push:
    branches:
      - halium-11.0

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Build Halium
        run: |
          sudo apt update
          sudo apt install android-tools-mkbootimg bc bison build-essential ca-certificates cpio curl flex git kmod libssl-dev libtinfo5 python2 sudo unzip wget xz-utils -y --no-install-recommends
          sudo ln -sf python2.7 /usr/bin/python
          sudo wget https://raw.githubusercontent.com/LineageOS/android_system_core/lineage-17.1/mkbootimg/mkbootimg.py -O /usr/bin/mkbootimg
          git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
          ./build/build.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: halium-build-artifacts
          path: |
            out/*

  devel-deploy:
    needs: build
    runs-on: ubuntu-20.04
    if: github.event_name == 'repository_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: halium-build-artifacts
          # Destination path
          path: out
          
      - name: Build Flashable
        run: |
          sudo apt update
          sudo apt install -y git img2simg jq sudo wget xz-utils
          git clone https://gitlab.com/ubports/community-ports/halium-generic-adaptation-build-tools -b halium-11 build
          DEVICE="$(source deviceinfo && echo $deviceinfo_codename)"
          ./build/prepare-fake-ota.sh out/device_$DEVICE.tar.xz ota
          mkdir -p out
          ./build/system-image-from-ota.sh ota/ubuntu_command out
          mv out/rootfs.img out/ubuntu.img
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: halium-flashable-artifacts
          path: |
            out/*

